### ISSUE TITLE
How to get the string back?

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/characters#23]
Suppose I have some text and I want to capitalize its first letter:

```dart
String text = "marcelo";
var chars = Characters(text);
chars = chars.take(1).toUpperCase() + chars.skip(1);
```

This is an `Iterable`, so as I understand, you can get the `String` by doing 

```dart
return chars.toString();
```

The `toString()` documentation says:  `/// The [string] content of these characters.`

But there is also a `string` getter that says `/// The string to iterate over.`

So, these two are always the same string? It must be, always. And indeed the implementation reads:

```dart
@override
  String toString() => string;
```

But no implementation can have `toString()` different than `string`. They are the same by definition (if I understood it correctly), so the documentation should clearly state this:

```dart
/// The string content of these characters. Same as using [toString].
String get string;

/// The string content of these characters. Same as using the [string] getter.
String toString();
```

In fact, I'd choose one of them and point it to the other in the abstract `Characters` class: 

```dart
String get string => toString();
```

or

```dart
@override
String toString() => string;
```

**Comment by lrhn** [comment]
The `string` getter provides the underlying string.

The `toString` method provides a printable representation of the characters. The best such representation happens to be the underlying string. 

The name `toString()` suggests a transformation (and indeed, it transforms the `Characters` class instance to a printable string).
The `string` getter extracts a property. It happens to be the *only* property of a `Characters` object.

So they two return the same value, even though they have different *purposes*. They should not be used interchangeably, you should use the one which fits what you are trying to do. If that thing isn't "building a new string", you should probably not be using `toString`.
