### ISSUE TITLE
Not clear how to map some String position to the Characters position, and vice-versa.

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/characters#24]
If you have some text in a `TextField` you can get the caret's (also called cursor) position. If you want to delete the character at the caret's position, you must be able to say that, say, the 7th position in the `String` maps to the 5th position in the `Characters`, so that you can delete this char.

The same problem arises if you want to add some character in the caret's position. 

But is there a way to do this? Doesn't seem so, or at least it's not obvious to me.

This is important, since the `TextField` will report positions in the `String`, not in the `Characters`. I suggest the following to methods:

```dart
int convertFromStringIndex(int stringIndex)
int convertFromCharactersIndex(int charactersIndex)
```

If you want to be really complete, you can also have these methods:

```dart
List<int> getAllStringIndexes()
List<int> getAllCharactersIndexes()
```

**Comment by lrhn** [comment]
I'd prefer to not expose indices in the `Characters` class API.

A more indirect approach would be constructors for the `CharacterRange` class which take a position, or a range, in the input code units, and then produces a  `CharacterRange` covering that position or range.

To go the other way, the `CharacterRange` has `stringBefore` and `stringAfter`, which can give you the code unit count before and after the range. We could easily add `stringBeforeLength` and `stringAfterLength` as well, to avoid unnecessary allocation when finding that length.

It's not an "index'. But it is, really.

**Comment by lrhn** [comment]
Some functionality added.
