### ISSUE TITLE
Add repository to pubspec.yaml

### ISSUE THREAD

**Issue by awhitford** [dart-lang/characters#38]
Trying to run [dart-flutter-favorite](https://github.com/kf6gpe/dart-flutter-favorite/) against a project, it stops because [characters](https://pub.dev/packages/characters) does not have a _GitHub Repository_ listed.

Can you please add the optional [repository](https://dart.dev/tools/pub/pubspec#repository) field to `pubspec.yaml` so that this tool can run successfully?

See https://github.com/kf6gpe/dart-flutter-favorite/issues/19

**Comment by lrhn** [comment]
I don't think *any* of the Dart-team's packages use the `repository` field, so it's surprising if `characters` is the only one you have issue with. They all have a `homepage` entry pointing to the repository, though.
