### ISSUE TITLE
क्षि is falsely coming back as 2 characters

### ISSUE THREAD

**Issue by rmargolinross** [dart-lang/characters#41]
Not sure why this is coming back as 2 characters as I believe it should be only 1

**Comment by natebosch** [comment]
https://onlineunicodetools.com/count-unicode-characters also counts this as 2 graphemes

Is there another library that you are using which counts this as 1 character?

**Comment by rmargolinross** [comment]
If you highlight the character in the browser, it highlights as one, so I expect it to count as one. Also it is typed as one character.

**Comment by natebosch** [comment]
@lrhn - Do you know if there are variations on the length algorithms for unicode characters that could explain this?

**Comment by lrhn** [comment]
The string is `"\u{0915}\u{094d}\u{0937}\u{093f}"`.
The characters have the following [general categories](http://www.unicode.org/reports/tr44/#GC_Values_Table) and categorization in the Unicode text segmentation algorithm:
* U+0915 क DEVANAGARI LETTER KA: Lo (Other_Letter), "other"
* U+094d ् DEVANAGARI SIGN VIRAMA: Mc (Nonspacing_Mark), [Extend](https://unicode.org/reports/tr29/#Extend)
* U+0937 ष DEVANAGARI LETTER SSA: Lo (Other_Letter), "other"
* U+093f ि DEVANAGARI VOWEL SIGN I: Mn (Spacing_Mark), [Spacing mark](https://unicode.org/reports/tr29/#SpacingMark)

The general grapheme cluster breaking algorithm [rules](https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules) do indeed make this two grapheme clusters.

The issue, if my quick study is right, is that the VIRAMA sign should bind to the next letter combination, but the *general* algorithm doesn't cover this. There is no category for "Devanagari Virama" in the breaking algorithm, and therefore no rules specially for it.
The Unicode spec [mentions](http://www.unicode.org/reports/tr44/#GC_Values_Table) that you can have special tailored tables that handle special cases, and this exact character combination is called out as an example ("Devanagari kshi"). 

The `characters` package does not have any such specialized tables. It would require recognizing a lot of special locale-specific characters which could blow up the tables it uses internally (also, there is no official list of those exceptions, so it's not easy to do).

So, special-case rules not part of the default general algorithm, and not supported by the characters package.
(Also not likely to be supported, it would require recognizing Devanagari Virama and Devanagari Consonant specifically and have extra rules for those, and then we would also want to incorporate all the other known exceptions.).
