### ISSUE TITLE
[Request] Refactor to Add and Use a Char Class

### ISSUE THREAD

**Issue by caseycrogers** [dart-lang/characters#43]
Right now, `Characters` and `CharacterRange` implement `Iterable<String>` and `Iterator<String>`, respectively. This is non-ideal because Characters and CharacterRange represent Iterables/Iterators of single character Strings, but this isn't in any way represented or enforced by the type system.

To make the API more clear and usable, the `Characters` package should include a `Char` class. `Char` should implement String and `Characters` and `CharacterRange` should implement `Iterable<Char>` and `Iterator<Char>` respectively. Because `Char` inherits from `String`, this should be a non breaking change.

**Comment by natebosch** [comment]
`String` is a sealed class so `Char` could not be a subtype of `String`.

I also think it's important that there _isn't_ a type which implements both `String` and `Characters` and those types have methods that overlap but have different behavior - like the `length` getter which could be different depending on whether you are considering the `String` length or `Characters` length. If you pass a `Char` to some API expecting a `String` it would be bad for that `length` to behave different from `String`, and vice-versa passing it to some API expecting a `Characters`.
