### ISSUE TITLE
Const constructor

### ISSUE THREAD

**Issue by Jjagg** [dart-lang/characters#48]
This is a feature request to make the unnamed `Characters` constructor const, or to add a `const Characters.empty` static field or constructor.

It seems the `Characters` constructor can be made `const`. This would enable user code to construct a `Characters` in constant expressions. E.g. constructors would be able to take a string and convert it to characters or create an empty characters and still be `const`.

I understand that this limits future design of `Characters`, since a const ctor would prohibit non-final or late variables which might be useful for example to cache `length`. For my use-case, I really only care about constructing an *empty* `Characters` in a `const` context. Adding a `const` constructor or static field for the empty `Characters` does not limit future design in the same way, because a factory constructor could be used that would hold up even if `StringCharacters`' ctor would be made non-const.

```dart
abstract class Characters implements Iterable<String> {
  const factory Characters.empty() = _EmptyCharacters;
}

class _EmptyCharacters implements Characters {
  // ...
}
```

For now, I've managed to work around this by directly constructing a `StringCharacters`, but that's not ideal because it's not part of the public API surface.

```dart
// ignore: implementation_imports
import 'package:characters/src/characters_impl.dart' as characters_impl;

const emptyChars = characters_impl.StringCharacters('');
```

**Comment by lrhn** [comment]
We already have the constant empty characters available, so we could either change the `Characters` constructor to:
```dart
/// An empty [Characters] containing no characters.
static const Characters empty = StringCharacters.empty;
/// Creates ....
///
/// Returns [empty] if [string] is empty.
factory Characters(String string) => string.isEmpty ? empty : StringCharacters(string);
```
or just make the factory constructor `const` directly. 
The former would make empty characters cheaper even for people who don't write `const` in front, and won't prevent us from adding caching in the future if we want to.

**Comment by lrhn** [comment]
There is now a `static const Characters empty` declaration.
