### ISSUE TITLE
Implement replaceRange and substring similar to String

### ISSUE THREAD

**Issue by erf** [dart-lang/characters#77]
Similar to the [String](https://api.dart.dev/stable/2.19.5/dart-core/String-class.html) methods, would it be possible to implement [replaceRange](https://api.dart.dev/stable/2.19.5/dart-core/String/replaceRange.html) and [substring](https://api.dart.dev/stable/2.19.5/dart-core/String/substring.html) ?

Something like this ?

```
extension CharactersExt on Characters {
  Characters substring(int start, [int? end]) {
    return skip(start).take((end ?? length) - start);
  }

  Characters replaceRange(int start, int? end, Characters replacement) {
    return substring(0, start) + replacement + substring(end ?? length);
  }
}
```

**Comment by lrhn** [comment]
If you know the indices, you should have them available as a `CharacterRange`. That's the useful way to specify a range of characters, because using indices into the character sequence just means the text-breaking algorithm needs iterate again to find the actual positions in the underlying string.

And there already is [`CharacterRange.replaceRange`](https://pub.dev/documentation/characters/latest/characters/CharacterRange/replaceRange.html) which does exactly what you're asking for.

In general, don't use indices. Use `CharacterRange` to represent ranges in a `Characters` object.

**Comment by erf** [comment]
I will have to look more into `CharacterRange`. Awesome package BTW ! I don't think many languages handles grapheme clusters this well and I'm having quite fun working on a text based console app with working emojis !

BTW, if i can ask a question a bit off topic .. are there some performance benefits of storing strings as `Characters` vs `Strings` (or even `CharacterRanges`) if you are doing a lot of manipulation?

**Comment by erf** [comment]
Maybe you could provide some examples on how to use `CharacterRange` and it's various methods to do certain things  e.g. delete a human readable character at a specific index.

**Comment by erf** [comment]
Here is some code i was able to create (with some help of ChatGPT (!)) using `CharacterRange` to delete a specific character in the middle of a string given an index? Do you have an suggestion of how this could be improved further? @lrhn 

```
import 'package:characters/characters.dart';

Characters removeCharacterAtIndex(Characters text, int index) {
  if (index < 0 || index >= text.length) {
    // Invalid index, return original text
    return text;
  }

  final range = CharacterRange.at(text.toString(), index, index + 1);
  range.replaceRange(Characters(''));

  return range.charactersBefore + range.charactersAfter;
}

void main() {
  Characters text = Characters('hello@world');
  int index = 5; // Index of the '@' character

  Characters modifiedText = removeCharacterAtIndex(text, index);
  print(modifiedText); // Output: helloworld
}
```

**Comment by erf** [comment]
Thanks for the feedback! I guess i was not far off with the last example. I understand why you don't want to use indexing as you explain the non-constant time could trick people into making bad use of the API. I guess my reason for wanting it, is because it is more intuitive as I'm used to these kind of API's, and was struggling to understanding these new API's (and maybe others are too?). Maybe adding more examples or a tutorial for this would help new users. And thanks for the heads up regarding the cost of the `length`. I'm playing around with building a text editor for the terminal which handles grapheme clusters correctly, where each line is a `Characters` object. I use a index for the cursor position, but also have to do some juggeling back and forth to be able to searches and various operations, but usually since i've broken the file into lines (for now), the operations are not that costly.

**Comment by erf** [comment]
If you have any idea or suggestion (or if there is a limitation) on using a large`Characters` object, e.g. for representing and manipulating a large string (e.g. a text file of 1000+ lines) please let me know.
