### ISSUE TITLE
The expected rendered width of unicode characters in the terminal

### ISSUE THREAD

**Issue by erf** [dart-lang/characters#78]
When i output characters to the terminal using `stdout.write` i notice that some characters take up one column width, whilst emoji characters usually takes up two columns. 

Would it be possible to determine the rendered column width per character and make it available via this package, or are there other factors that determine this we don't have control over? (like the terminal, font, etc).

The reason i would like this is that I would like to position my cursor correctly in the terminal based on how much space the emojis and other various characters take up. 

Sorry if this question is out of scope for this library.

**Comment by lrhn** [comment]
This seems outside of the scope of this package. Rendering depends on the target canvas, available fonts and whatever strategies the rendering application uses. Writing into a fixed-width character grid is very non-trivial.

If rendering is *correct*, I'd expect each grapheme cluster to be one character.
How "one character" is rendered, ... that's magic.

Not even going to try, sorry :)

**Comment by erf** [comment]
If not the rendered width, would it be possible to give some meta-data per for a given character index? I'm especially interested in the `text` vs `emoji` presentation, or if it has a VS15 or VS16 character to determine this. I see you already have all the Unicode data available.

**Comment by lrhn** [comment]
I'm sure someone can do something like this (well, fairly sure), but it won't be in this package. It's too far from the core competence or functionality of the existing code. It'd have to be a new and completely separate functionality on the side, which means it can just as well be in another package.
