### ISSUE TITLE
[Feature Request] Support `isEmoji`

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/characters#93]
### Context

https://github.com/flutter/flutter/issues/142037 is the issue that spawned this one.

### Request

When working with user-generated text, it can be helpful to introspect on that text, filter it, etc. Since text can include emojis, and this package provides ways of splitting text into its grapheme clusters such that each cluster (as I understand it, I'm new to this) could or could not represent an emoji, it would be awesome to have an `isEmoji` function similar to the one provided in [Swift](https://developer.apple.com/documentation/swift/unicode/scalar/properties-swift.struct/isemoji). Is this possible? I understand that its implementation may need to be updated as new emojis are added, so it may be undesirable. But given that the linked implementation above exists, I imagine Apple has decided it's worth the extra maintenance to have the nice DX.

Example usage:
```dart
extension on String {
  String withoutEmojis() {
    final buffer = StringBuffer();
    for (final cluster in characters) {
      if (!cluster.isEmoji) {
        buffer.write(cluster);
      }
    }
    return buffer.toString();
  }
}
```

**Comment by xvrh** [comment]
I think you can write an `isEmoji` extension like this:

```dart
extension on String {
  static final _isEmojiRegex =
      RegExp(r'\p{Extended_Pictographic}', unicode: true);

  bool get isEmoji {
    return _isEmojiRegex.hasMatch(this);
  }
}

```

**Comment by btrautmann** [comment]
> I think you can write an `isEmoji` extension like this:

Unfortunately I don't think that will be exhaustive, consider the following using that implementation:

```dart
void main() {
  const family = '👨‍👩‍👦‍👦';
  print(family.isEmoji);  // prints `true`
  
  const usa = '🇺🇸';
  print(usa.isEmoji); // prints `false`
}
```

**Comment by xvrh** [comment]
Maybe with the regex like that:

```dart
  static final _isEmojiRegex = RegExp(
      r'[\p{Extended_Pictographic}\p{Emoji_Presentation}]',
      unicode: true);
```

**Comment by btrautmann** [comment]
> Maybe with the regex like that:
> 
> ```dart
>   static final _isEmojiRegex = RegExp(
>       r'[\p{Extended_Pictographic}\p{Emoji_Presentation}]',
>       unicode: true);
> ```

This seemingly works at least for my use case. I do think it'd be sweet to have this as an extension managed by the framework rather than something every user that needs the functionality maintains, so I won't immediately close this unless a maintainer disagrees :)

**Comment by erf** [comment]
Do you guys have a link to where this regex pattern is documented? That is using `Extended_Pictographic` and `Emoji_Presentation`. I couldn't find it mentioned in [RegExp](https://api.dart.dev/stable/3.2.6/dart-core/RegExp-class.html) and i'm surprised you can query those. I do however think a more low level construct would be better performance wise than a regex. The `Characters` package already have the `emoji-data` table available, but not sure if this is out of scope, as it's mainly for iterating grapheme clusters.

**Comment by btrautmann** [comment]
Not sure if this helps, but they're documented (IMO) pretty well here:
- https://unicode.org/reports/tr51/#Emoji_Characters
- https://unicode.org/reports/tr51/#Emoji_Properties_and_Data_Files

**Comment by lrhn** [comment]
Not planned as part of this package. It has precsely one goal: Grapheme cluster segmentation.
It does not try to interpret the code points beyond what is needed for segmentation.

It might be possible to use the same tables to recognize, fx, emojis, but it's probably accidental that emojis are treated specially by graheme cluster segmentation, and it's quite possible that the tables do not have all the necessary information to detect emojis both correctly and precisely.
